### ISSUE TITLE
DI features for Unobtrusive integration with existing system or legacy code

### ISSUE THREAD

**Issue by dadhi** [ashmind/net-feature-tests#21]
There are number of features that may be important (even deciding factor) for people to introduce IoC into current code. Especially in legacy systems it should be possible to start using Container incrementally, then refactoring to the better code.

Features may start with:
* Injecting primitive values.
* Support for default parameters.
* Support for factory methods (static and instance) in addition to constructor.

I know that most of these things could be done with Delegate Registration, but it is less refactoring friendly, or sometimes is not feasible for Runtime scenarios (when types are not known). The latter is common for plugin systems.

The above also may be treated as _Convenience_, but I would like to separate.

**Comment by ashmind** [comment]
I think it makes sense to split remaining parts here (1. parameter names 2. factory methods) -- then I'll just close this one.

**Comment by dadhi** [comment]
Yes,  make sense.

**Comment by dadhi** [comment]
I have added wiki page in DryIoc for using methods and properties/fields as service factories:
May help with test implementation. Placing link here to not forget: https://bitbucket.org/dadhi/dryioc/wiki/SelectConstructorOrFactoryMethod#markdown-header-propertyfield-as-factory-method

**Comment by ashmind** [comment]
Thanks, I'll take a look!
Closing this one -- I've not decided on when/whether, but I'll track remaining parts separately under #30/#31.
