### ISSUE TITLE
TinyIoC in DI container comparison

### ISSUE THREAD

**Issue by philippgille** [ashmind/net-feature-tests#26]
As mentioned in our e-mail conversation:

On [your DI container comparison website](http://featuretests.apphb.com/DependencyInjection.html) you say regarding [TinyIoC](https://github.com/grumpydev/TinyIoC):
> Code-only NuGet package

I wasn't sure what you meant with that, so you clarified:
> I ignored source-only containers mostly because of nuget update concerns (and because I wanted to encourage proper dlls)

I just searched for it and it looks as if TinyIoC is available on NuGet now: [http://www.nuget.org/packages/TinyIoC/](http://www.nuget.org/packages/TinyIoC/). It would be great if you could add it to the comparison, because it's being used in the popular REST framework Nancy by default and it would be interesting to know if it makes sense to switch to another DI container from the beginning or if you're good to go with TinyIoC until you need some advanced features.

**Comment by ashmind** [comment]
Thanks! I have a few other items on my OSS backlog at the moment, but I hope to look at it this week.

**Comment by philippgille** [comment]
Awesome, thank you so much!

I see you also removed TinyIoC from the "Not tested" list ([in here](DependencyInjection/Html/AfterAll.html
)), but it still appears there when I visit http://featuretests.apphb.com/DependencyInjection.html. Can you confirm this, or is it just me?

**Comment by ashmind** [comment]
@philippgille Seems like a bug -- I probably haven't regenerated the results after removing it.
It's minor, but I'll still take a look later today.

**Comment by ashmind** [comment]
Done -- latest re-generation removed it.
