### ISSUE TITLE
Mono compatibililty

### ISSUE THREAD

**Issue by mika76** [ashmind/net-feature-tests#28]
In the graph it states that Unity is not mono compatible, but it says here it supports it https://unity.codeplex.com/wikipage?title=Unity3.5ReleaseNotes

**Comment by ashmind** [comment]
Hm, that's auto-generated based on a NuGet package. I suppose Xamarin might work with packages that do not explicitly list Xamarin as well -- if so I'll probably just filter out Mono from that table.

**Comment by mika76** [comment]
I see. I think mono compatibility is becoming more and more important, so it's probably a good idea :smile:
