### ISSUE TITLE
Unity works in .Net 4.0

### ISSUE THREAD

**Issue by Mani-G** [ashmind/net-feature-tests#34]
We are using DI Container for our projects with .Net 4.0 2 years before.
Please correct the metrics

**Comment by dotnetjunkie** [comment]
The tests clearly state:

> This information is based on versions included in NuGet package.

The [NuGet package of the latest Unity version](https://www.nuget.org/packages/unity/) does not support .NET 4.0.

So I don't think there is anything that @ashmind can correct here.
